services:
  postgres:
    image: postgres:14
    env_file: .env.local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations
    networks:
      - finance_api_network

  # app:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: finance_api
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?sslmode=disable
  #   depends_on:
  #     - postgres
  #   networks:
  #     - finance_api_network

volumes:
  postgres_data:

networks:
  finance_api_network:
    driver: bridge